server:
  port: 8090

spring:
  mongodb:
    username: admin
    password: admin
    additional-hosts: localhost
    port: 27017
    database: customer
    authentication-database: admin

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}